"""
Module for the work on the Piston Reconstruction Experiment (P-REx) see Pott et al 2016
Produced by Felix Widmann as part of the master thesis at MPIA in Heidelberg

This module contains classes & functino for image processing directly on the output of an
AO System. It contains 3 Parts right now:

Part 1: zernike.py
	Functions to reconstruct images from Zernike modes
Part 2: imagepro.py
	Functions for image processing, main focus on cross-correalations and gauss-fitting
Part 3: pistonrec.py
	Functions for the actual prex algorithm
Part 4: yaodata.py
	In order to apply the prex algorithms to data generated by the Yorick Adaptive Optics
	simulation (YAO, from Francois Rigaut: http://frigaut.github.io/yao/index.html).
	To be used, one has to modify the Yao files a little to get the right data. Examples
	for that will be added.

!!! This Module is under constant developement at the moment !!!

"""

from .zernike import *
from .imagepro import *
from .pistonrec import *
from .yaodata import *
	
