###########
## Main file of the Python Module P-Rex, a module for test for a 
## piston reconstruction experiement for optical interferometer (see Pott et al 2016)
##
## Copyright (c) 2017, Felix Widmann
##
## This program is free software; you can redistribute it and/or  modify it
## under the terms of the GNU General Public License  as  published  by the
## Free Software Foundation; either version 2 of the License,  or  (at your
## option) any later version.
###########



###########
## Module for the work on the Piston Reconstruction Experiment (P-REx) see Pott et al 2016
## Produced by Felix Widmann as part of the master thesis at MPIA in Heidelberg
## 
## This module contains classes & functino for image processing directly on the output of an
## AO System. It contains 6 Parts right now:
## 
## Part 0: smallfunc.py
##  Some small functions used for plotting and general calculations
## Part 1: zernike.py
## 	Functions to reconstruct images from Zernike modes
## Part 2: imagepro.py
## 	Functions for image processing, main focus on cross-correalations and gauss-fitting
## Part 3: pistonrec.py
## 	Functions for the actual prex algorithm
## Part 4: yaodata.py
## 	In order to apply the prex algorithms to data generated by the Yorick Adaptive Optics
## 	simulation (YAO, from Francois Rigaut: http://frigaut.github.io/yao/index.html).
## 	To be used, one has to modify the Yao files a little to get the right data. Examples
## 	for that will be added.
## Part 5: flao.py
##  apply prex to flao data (more to come)
###########

from .smallfunc import *
from .zernike import *
from .imagepro import *
from .pistonrec import *
from .yaodata import *
from .flao import *
	
